Swiss statistics days 2024
SwissDataScienceCenter/renku-blog pull request #139
Opened 2024-09-16 09:55 UTC by bethcg

2024-09-17 13:40 UTC, lokijuhy commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +  and 5th 2024 in Aarau (Switzerland). This meeting gathered specialists related to
```suggestion
  and 5th 2024 in Aarau (Switzerland) and brought together specialists related to 
```

2024-09-17 13:40 UTC, lokijuhy commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +  statiscis domain across private and public sectors. The SDSC contribution “Renku: a platform
```suggestion
  statistics domain across private and public sectors. The SDSC contribution “Renku: a platform 
```

2024-09-17 13:43 UTC, lokijuhy commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +on Sept. 4th and 5th 2024 in Aarau (Switzerland). It gathered specialists related to
```suggestion
on Sept. 4th and 5th 2024 in Aarau (Switzerland) and brought together specialists related to
```

2024-09-17 13:45 UTC, lokijuhy commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +code repositories. Thus, Renku 2.0 can launch different types of sessions on top of them,
```suggestion
code repositories. These data and code come to life in Renku sessions,
```

2024-09-17 13:45 UTC, lokijuhy commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +that they select. Having these three components under the same umbrella makes it easier to
```suggestion
that they select. Having data, code, and compute under the same umbrella makes it easier to
```

2024-09-23 07:20 UTC, leafty commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +<!-- truncate -->
Honestly, you should truncate after the first paragraph. This does not look engaging at all:

![Screenshot 2024-09-23 at 09 18 44](https://github.com/user-attachments/assets/aaac6811-07a4-42c9-b5d3-f65cfcbe0401)

2024-09-23 07:20 UTC, leafty commented on blog/2024-09-11-swiss-statistics-days/index.mdx
> +image: ./image_1.png
Image for SEO/link previews should be landscape.

2024-09-23 07:20 UTC, leafty submitted a review, later dismissed

2024-09-27 14:34 UTC, lokijuhy requested changes
There's something off with the image- it renders unusually small.

2024-10-01 07:55 UTC, lokijuhy approved these changes

2024-10-01 07:59 UTC, merged