Personalized health technologies workshop
SwissDataScienceCenter/renku-blog pull request #140
Opened 2024-09-16 10:03 UTC by bethcg

2024-09-17 13:50 UTC, lokijuhy requested changes
Haha did you use the abstract I tried to re-write for them but they didn't accept? Glad it's getting used after all! 😆 

Minor suggestions...

2024-09-17 13:50 UTC, lokijuhy commented on blog/2024-08-30-PHRT-workshop/index.mdx
> +integrate their own research data and code into the Renku platform. Thus, participants
```suggestion
integrate their own research data and code into the Renku platform. In addition, participants
```

2024-09-17 13:50 UTC, lokijuhy commented on blog/2024-08-30-PHRT-workshop/index.mdx
> +provided valuable feedback about new requirements and necessary extensions.
Want to add a line thanking our workshop participants?

2024-09-23 07:22 UTC, leafty commented on blog/2024-08-30-PHRT-workshop/index.mdx
> +<!-- truncate -->
Truncate after some text, this is not engaging.

2024-09-23 07:22 UTC, leafty approved these changes

2024-10-01 07:10 UTC, merged