First draft of Renku 2.0 post
SwissDataScienceCenter/renku-blog pull request #45
Opened 2024-03-21 20:06 UTC by bethcg

2024-03-21 20:06 UTC, bethcg reviewed
First draft of Renku 2.0

2024-03-21 21:42 UTC, rokroskar commented
@bethcg I added some intro text and made some edits. Btw, I don't think we should link to the google slides but instead generate a pdf, put it in the shared drive, and link to that.

2024-03-22 16:13 UTC, lokijuhy requested changes
This looks great! I made some wordsmithing suggestions. 
More generally- I think we can use a more related cover image-? Renku 2.0 isn't about DevOps. I'll put ideas in our slack channel

2024-03-22 16:13 UTC, lokijuhy commented on blog/2024-03-22-renku-2-0/index.mdx
> +- Check out the [roadmap](https://docs.google.com/presentation/d/1-W56dVgsR2yzrq2slA1EIyVso10jlkSazce4xOOKIZE/edit?usp=sharing)
I would rather link to the public roadmap in the design docs
```suggestion
- Check out our [roadmap](https://github.com/SwissDataScienceCenter/renku-design-docs/blob/main/roadmap.md)
```

2024-03-22 16:13 UTC, lokijuhy commented on blog/2024-03-22-renku-2-0/index.mdx
> +
```suggestion
- Give feedback on our [design docs](https://github.com/SwissDataScienceCenter/renku-design-docs/tree/main)

```

2024-03-22 16:13 UTC, lokijuhy commented on blog/2024-03-22-renku-2-0/index.mdx
> +storage, they may be used in read-only or in read-write mode. However, projects
I think the read/write functionality is an unnecessary level of detail for this post. 
```suggestion
sources to their projects, such as S3 buckets and WebDAV resources. Projects
```

2024-03-22 16:13 UTC, lokijuhy commented on blog/2024-03-22-renku-2-0/index.mdx
> +Renku’s role is about making it easy for researchers to **mix and match** the elements they need to get their work done. In addition, Renku makes these elements **searchable**, encourages their **reu
```suggestion
Renku’s role is about making it easy for researchers to **mix and match** the elements they need to get their work done. In addition, Renku makes these elements **searchable**, encourages their **reuse** between projects, and **illuminates connections** between them (even across projects) wherever needed. Renku accomplishes this by extracting and indexing useful metadata about each of those elements.
```

2024-03-25 13:37 UTC, lokijuhy requested changes
Looking great! I suggested to modify the roadmap link, and have the Webinar slides as a separate link.

2024-03-25 13:37 UTC, lokijuhy commented on blog/2024-03-22-renku-2-0/index.mdx
> +- Check out the [roadmap](https://drive.google.com/file/d/1empUHHTonffW1fhdB_3DCIH-yVUz3MU8/view?usp=share_link)
```suggestion
- Watch our [Renku 2.0 webinar](https://youtu.be/6J0INjPFQd4) or view the [slides](https://drive.google.com/file/d/1empUHHTonffW1fhdB_3DCIH-yVUz3MU8/view?usp=share_link)
- Check out the [Renku roadmap](https://github.com/SwissDataScienceCenter/renku-design-docs/blob/main/roadmap.md)
```

2024-03-25 14:22 UTC, lokijuhy submitted a review, later dismissed
🎆

2024-03-26 09:17 UTC, lokijuhy commented on blog/2024-03-22-renku-2-0/index.mdx
> +stack. Furthermore, we plan to allow users to connect their Renku projects to to
```suggestion
stack. Furthermore, we plan to allow users to connect their Renku projects to
```

2024-04-04 07:33 UTC, lokijuhy approved these changes

2024-04-04 07:34 UTC, merged